# Generated by Django 5.2.17 on 2026-08-17 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('shipment_type', models.CharField(max_length=100)),
                ('cargo_type', models.CharField(blank=True, max_length=100)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_responded', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=30, unique=True)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('shipment_type', models.CharField(choices=[('air', 'Air Freight'), ('sea', 'Sea Freight (FCL)'), ('lcl', 'Sea Freight (LCL)'), ('road', 'Road Transport'), ('courier', 'Express Courier')], max_length=20)),
                ('status', models.CharField(choices=[('confirmed', 'Order Confirmed'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('customs', 'Customs Clearance'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='confirmed', max_length=20)),
                ('eta', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='freight.quoterequest')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Order Confirmed'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('customs', 'Customs Clearance'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='freight.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Event',
                'verbose_name_plural': 'Shipment Events',
                'ordering': ['occurred_at'],
            },
        ),
    ]
